[pytest]
django_find_project = false
pythonpath = ./tests/_demoapp/ ./src
DJANGO_SETTINGS_MODULE = demo.settings
norecursedirs = demo,.tox
addopts =
    --capture=no
    --tb=short
    --reuse-db
    --cov=streaming
    --cov-config=tests/.coveragerc
    --cov-report html

python_files =
    tests/test_*.py
    tests/**/test_*.py
    src/*.py

markers =
    functional: mark a test as functional
    selenium: selenium test
    skip: skip test
    online: mark a test as requiring network access
    withoutresponses: disable responses mocking
